apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    keyvaultName: "<YourKeyVaultName>"
    useVMManagedIdentity: "true"  # Uses the add-on's managed identity
    tenantId: "<YourAzureTenantId>"
    secrets: |
      array:
        - |
          secretName: "DatabasePassword"  # Name in Azure Key Vault
          objectName: "DB_PASSWORD"      # Env variable name in K8s
        - |
          secretName: "ApiKey"
          objectName: "API_KEY"
